Dev 14  firebase
Fnami51/SkyProFitnes pull request #14
Opened 2024-09-11 00:14 UTC by Balaura

1) Так как были ошибки в консоли браузера:
а) Warning: Invalid DOM property fill-rule. Did you mean fillRule?
б) Warning: Invalid DOM property clip-rule. Did you mean clipRule?
Чтобы исправить их исправить я заменила:
fill-rule на fillRule
clip-rule на clipRule
Эти ошибки были связаны с использованием атрибутов SVG в React. В React нужно использовать camelCase для атрибутов, даже для SVG.

2) Объединила в папку pages компоненты-страницы.

3) Везде где встречалось Profil, заменила на Profile

4) Выполнено подключение к firebase. 

5) Подключена авторизация / регистрация / сброс пароля

2024-09-11 09:45 UTC, Fnami51 requested changes
Впринципе всё хорошо. Единственное там есть серьёзные конфликты, нужно их вручную сделать и перебрать. Там в конфликтах есть такая фигня, что нужен кот и от входящего и от текущего. Внимательно посмотри это.

2024-09-11 09:45 UTC, Fnami51 commented on src/types/index.ts
Хорошо, единственное файл лучше по другому назвать. Напимер interfaces.ts. потому что потом в поиске можем запутаться

2024-09-11 09:45 UTC, Fnami51 commented on src/pages/ProfilePage/ProfilePage.tsx
> -            <Profil name="Sergei" login="serg228" password="qwertyu" url_img=""/>
Зачем ты решила профиль перенести сюда?

2024-09-11 19:14 UTC, Balaura commented on src/pages/ProfilePage/ProfilePage.tsx
> -            <Profil name="Sergei" login="serg228" password="qwertyu" url_img=""/>
О! Спасибо! Этот код делала глубокой ночью. Исправила.

2024-09-14 06:50 UTC, Artemisfree approved these changes

2024-09-15 12:51 UTC, Fnami51 approved these changes

2024-09-15 13:13 UTC, merged