DEV-4 added CoursePage, fixed global styles tailwind, added images
Fnami51/SkyProFitnes pull request #2
Opened 2024-08-23 16:19 UTC by Artemisfree

Сделал страницу для курса йоги. Адаптив для мобилки. Немного подправил глобальные стили tailwind для нормального отображения.

2024-08-23 16:37 UTC, Fnami51 reviewed
Добавил пару комментариев. Меня больше всего смущает по поводу CSS файлов, будем их использовать, а самое главное, можем ли мы их использовать

2024-08-23 16:37 UTC, Fnami51 commented on sky-pro-fitnes/public/images/yoga.jpg
Думаю эти картинки нам придётся брать из АПИ. Потом их надо убрать, пока пусть будут для вёрстки

2024-08-23 16:37 UTC, Fnami51 commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.module.css
Насколько я понял по заданию мы должны использовать только TailwindCSS, а это модульный CSS. Мне кажется, что мы должны отказаться от остальных css файлов, кроме талвиндовских. Подправь меня если я не прав.

2024-08-23 22:15 UTC, Balaura requested changes

2024-08-23 22:15 UTC, Balaura commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +				<h2 className='pt-[40px] ml-[40px] text-[60px] text-white w-[300px] h-[66px] flex items-center text-center relative z-10 mobile:hidden'>
Здесь стоит убрать размеры weight и height (при них ломается верстка). Добавить line-height: 66px. И поставить font-weight: 500.

Код для замещения:
`<h2 className='pt-[40px] ml-[40px] leading-[66px] text-[60px] font-medium text-white flex items-center text-center relative z-10 mobile:hidden'>
					Йога
				</h2>`

2024-08-23 22:15 UTC, Balaura commented on sky-pro-fitnes/src/App.tsx
> +		<div className='bg-background min-h-screen flex flex-col px-[16px] mobil:px-[16px] desktop:px-[70px] mediumDesktop:px-[140px] pb-page-padding overflow-x-hidden w-screen'>
w-screen ломает верстку и добавляет горизонтальную прокрутку

2024-08-23 22:15 UTC, Balaura commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +						Начните путь
![image](https://github.com/user-attachments/assets/84162988-c4e4-4865-9b2a-5796d26633e4)
Почему-то не совпадают шрифты. Скиньте пожалуйста свои скриншоты, может у меня что-то?
Также выравнивание пунктов съехало.

2024-08-23 22:15 UTC, Balaura commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +					<li className='flex items-center gap-[3.25px]'>
Здесь и далее gap 8px по макету.

2024-08-23 22:15 UTC, Balaura commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +					<button className='bg-[#BCEC30] text-black font-roboto text-[16px] font-normal leading-[17.6px] text-center w-[437px] h-[52px] rounded-[46px] px-[26px] py-[16px] transition-all duration-300 ease
Здесь 18 шрифт

2024-08-23 22:40 UTC, Fnami51 commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +						Начните путь
Проверь подключён ли 500-ый размер

2024-08-23 22:44 UTC, Fnami51 approved these changes
В принципе считаю если какие-то недочёты вылезут, то их легко подправить. Это всего лишь вёрстка. По коду окей. Проект не запускал саму вёрстку не смотрел

2024-08-24 16:44 UTC, Artemisfree commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +				<h2 className='pt-[40px] ml-[40px] text-[60px] text-white w-[300px] h-[66px] flex items-center text-center relative z-10 mobile:hidden'>
Поменял

2024-08-24 16:45 UTC, Artemisfree commented on sky-pro-fitnes/src/App.tsx
> +		<div className='bg-background min-h-screen flex flex-col px-[16px] mobil:px-[16px] desktop:px-[70px] mediumDesktop:px-[140px] pb-page-padding overflow-x-hidden w-screen'>
убрал

2024-08-24 16:54 UTC, Artemisfree commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +						Начните путь
Подключил

2024-08-24 17:00 UTC, Artemisfree commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +					<button className='bg-[#BCEC30] text-black font-roboto text-[16px] font-normal leading-[17.6px] text-center w-[437px] h-[52px] rounded-[46px] px-[26px] py-[16px] transition-all duration-300 ease
поменял

2024-08-25 13:11 UTC, Balaura approved these changes
Остались только пункты. Но это уже мелочь.

2024-08-25 13:11 UTC, Balaura commented on sky-pro-fitnes/src/components/CoursePage/CoursePage.tsx
> +						Начните путь
Осталось только выравнивание и размер пунктов списка:
![image](https://github.com/user-attachments/assets/cf35c0f7-c930-4433-b25b-170249b778a7)

2024-08-25 21:34 UTC, merged