Dev 27  Вёрстка главной страницы и профиля
Fnami51/SkyProFitnes pull request #4
Opened 2024-08-26 08:42 UTC by Fnami51

![изображение](https://github.com/user-attachments/assets/e04b4ae3-c317-46b3-bf0b-2fab12597f9a)
![изображение](https://github.com/user-attachments/assets/fdfded0b-2b8a-4ba5-a4f1-b1d567a247ff)
![изображение](https://github.com/user-attachments/assets/aee9cdc4-b776-4e4f-9180-011fa06b0634)

Пока, чтобы лучше всё отследить, все компоненты Page можно закинуть в App.tsx

2024-08-26 09:37 UTC, Artemisfree requested changes

2024-08-26 09:37 UTC, Artemisfree commented on sky-pro-fitnes/src/components/Cards/CourseCard.tsx
> +                        <p>Сложность</p>
Отличается от дизайна. Отстуствует значок у сложности.
<img width="323" alt="Снимок экрана 2024-08-26 в 12 26 01" src="https://github.com/user-attachments/assets/e52040a8-1320-40ad-9cb9-67cca06f54bc">
<img width="179" alt="Снимок экрана 2024-08-26 в 12 29 22" src="https://github.com/user-attachments/assets/71a0f7b8-f31a-4fae-8408-ba85157f44c5">

2024-08-26 09:37 UTC, Artemisfree commented on sky-pro-fitnes/src/components/Cards/MyCourseCard.tsx
> +                        <p>Сложность</p>
Здесь тоже самое

2024-08-26 09:37 UTC, Artemisfree commented on sky-pro-fitnes/src/components/MainPage/MainPage.tsx
> +                <CourseCard name="Йога" day={25} time="25-30" url_img="/images/yoga_small.png" />
не правильно позиционирована картинка
<img width="323" alt="Снимок экрана 2024-08-26 в 12 26 01" src="https://github.com/user-attachments/assets/85b97ffe-7c9c-4531-a569-f6a032ba2b9d">

2024-08-26 09:37 UTC, Artemisfree commented on sky-pro-fitnes/src/components/ProfilPage/ProfilPage.tsx
> +                <MyCourseCard name="Йога" day={25} time="25-30" url_img="/images/yoga_small.png" progress={40} />
Здесь так же

2024-08-26 09:37 UTC, Artemisfree commented on sky-pro-fitnes/src/components/ProfilPage/Profil.tsx
не адаптировано под мобильную версию

2024-08-26 09:37 UTC, Artemisfree commented on sky-pro-fitnes/src/components/MainPage/MainPage.tsx
не адаптировано под мобильную версию
<img width="731" alt="Снимок экрана 2024-08-26 в 12 25 37" src="https://github.com/user-attachments/assets/a84d3157-f4d1-4455-8d2a-a41f67a052a3">
<img width="701" alt="Снимок экрана 2024-08-26 в 12 25 31" src="https://github.com/user-attachments/assets/8f5ef13c-188a-42a3-84c1-b1a7bd695d15">

2024-08-26 09:41 UTC, Artemisfree requested changes

2024-08-26 09:41 UTC, Artemisfree commented on sky-pro-fitnes/src/components/Cards/CourseCard.tsx
> +                        <p>{time} мин/день</p>
не правильные отступы
<img width="214" alt="Снимок экрана 2024-08-26 в 12 38 50" src="https://github.com/user-attachments/assets/228d0e09-3913-4754-ac5a-3b61f1736836">
<img width="219" alt="Снимок экрана 2024-08-26 в 12 38 59" src="https://github.com/user-attachments/assets/8143e756-08d4-4dd9-90b8-16ee62fdf585">

2024-08-26 09:41 UTC, Artemisfree commented on sky-pro-fitnes/src/components/Cards/MyCourseCard.tsx
> +                        <p>{time} мин/день</p>
тоже самое

2024-08-26 10:09 UTC, Fnami51 commented on sky-pro-fitnes/src/components/MainPage/MainPage.tsx
> +                <CourseCard name="Йога" day={25} time="25-30" url_img="/images/yoga_small.png" />
Картинку думаю потом всё равно будем из апи подтягивать. потому что курсов может быть больше

2024-08-27 08:54 UTC, Artemisfree approved these changes

2024-08-27 15:43 UTC, Balaura requested changes
![image](https://github.com/user-attachments/assets/5192a4e7-dd15-4f9b-a026-cf6ef8a95025)
![image](https://github.com/user-attachments/assets/e310345f-82de-4ac0-a93e-e7e395c7a2f7)
В макет не влезает совсем.

2024-08-27 15:43 UTC, Balaura commented on sky-pro-fitnes/src/components/MainPage/MainPage.tsx
> +                    Начните заниматься спортоми улучшите качество жизни
Нужен пробел: "спортом и" и gap тут: `<article className='flex gap-[30px]'>` не 30px а хотя бы 25px, иначе при макетной ширине фраза не вмещается.

2024-08-29 10:08 UTC, Balaura approved these changes

2024-08-29 10:52 UTC, merged